- name: copy ssh config
  template:
    src: config
    dest: "/home/{{ cluster_admin }}/.ssh/config"
    owner: "{{ cluster_admin }}"
    group: "{{ cluster_admin }}"
    mode: '0400'

- name: copy ssh config to root
  template:
    src:   config
    dest:  /root/.ssh/config
    owner: root
    group: root
    mode: '0400'

