#!/bin/bash
EVENT_LOG=/tmp/event-failed.log

if [ -f $EVENT_LOG ]; then
   date >> $EVENT_LOG
else
   date >  $EVENT_LOG
fi

env >> $EVENT_LOG
echo >> $EVENT_LOG
echo "-------------------" >> $EVENT_LOG

